include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    asset_does_not_exist: ignore
    asset_directory_does_not_exist: ignore

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
